[package]
name = "postcard-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard-bindgen-proc-macro = {path = "../postcard-bindgen-proc-macro"}
postcard-bindgen-core = {path = "../postcard-bindgen-core"}

[dev-dependencies]
serde = "1"
serde_derive = "1"