[package]
name = "postcard-bindgen"
version = "0.1.1"
edition = "2021"
authors = ["Alexander Hübener <alex.teamplayer@gmail.com>"]
repository = "https://github.com/teamplayer3/postcard-bindgen.git"
description = "A crate to generate bindings for the postcard binary format for other languages than Rust."
keywords = ["postcard", "generating", "javascript", "serde", "serialize"]
categories = ["embedded", "encoding", "no-std"]
license = "MIT OR Apache-2.0"
readme = "../README.md"

[features]
default = []
std = ["postcard-bindgen-core/std"]
alloc = ["postcard-bindgen-core/alloc"]
heapless = ["postcard-bindgen-core/heapless"]

[dependencies]
postcard-bindgen-derive = {version = "0.1.1", path = "../postcard-bindgen-derive"}
postcard-bindgen-core = {version = "0.1.1", path = "../postcard-bindgen-core"}

[dev-dependencies]
serde = "1"
serde_derive = "1"
postcard = "1.0.2"

[[example]]
name = "generate_bindings"
required-features = ["std"]