[package]
name = "postcard-js-test"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard-js-proc-macro = {path = "../postcard-js-proc-macro"}
postcard-js-lib = {path = "../postcard-js-lib"}

serde = "1"
serde_derive = "1"