[package]
name = "no-std"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"], default-features = false }
postcard-bindgen = { path = "../../postcard-bindgen" }


[workspace]
members = [
    "gen-bindings"
]