[package]
name = "postcard-bindgen-core"
version = "0.1.1"
edition = "2021"
authors = ["Alexander Hübener <alex.teamplayer@gmail.com>"]
repository = "https://github.com/teamplayer3/postcard-bindgen.git"
description = "A crate to generate bindings for the postcard binary format for other languages than Rust - Core Crate"
keywords = ["postcard", "generating", "javascript", "serde", "serialize"]
categories = ["embedded", "encoding", "no-std"]
license = "MIT OR Apache-2.0"
readme = "../README.md"

[features]
default = []
alloc = []
heapless = ["dep:heapless"]
std = ["alloc"]

[dependencies]
genco = "0.17.2"
convert_case = "0.6.0"
heapless = { version = "0.7.16", optional = true }
serde = {version = "1.0", features = ["derive"]}